<?php

declare(strict_types=1);

namespace Docuconf\Export;

use Docuconf\Duration;
use Docuconf\Spec\ContractSpec;
use Docuconf\Spec\FileSpec;
use Docuconf\Spec\VarSpec;
use Docuconf\Version;

/**
 * Turns a contract into `contract.cue` (SPEC §4): the generated-code header,
 * a package clause, the meta-schema import, then `contract.#Contract & {...}`
 * as plain data. Variables and files are sorted by name, so the output is
 * deterministic.
 */
final class Exporter
{
    public const HEADER = '// Code generated by docuconf. DO NOT EDIT.';

    public static function toCue(ContractSpec $contract, ?string $package = null): string
    {
        $package ??= self::packageName($contract->name);
        return self::HEADER . "\npackage $package\n\nimport \"docuconf.dev/contract\"\n\ncontract.#Contract & "
            . Cue::struct(self::toArray($contract), 0) . "\n";
    }

    /**
     * The contract as data, in the field order the exporter writes. This is
     * also the contract's JSON form (`cue export`), as contract-first mode
     * reads it, except that defaults are not filled in.
     *
     * @return array<string, mixed>
     */
    public static function toArray(ContractSpec $contract): array
    {
        $metadata = ['name' => $contract->name];
        if ($contract->appVersion !== null) {
            $metadata['appVersion'] = $contract->appVersion;
        }
        $metadata['generator'] = ['language' => 'php', 'sdk' => Version::SDK, 'version' => Version::VERSION];
        $out = [
            'apiVersion' => 'docuconf.dev/v1alpha1',
            'kind' => 'ConfigContract',
            'metadata' => $metadata,
            'vars' => [],
        ];
        foreach ($contract->sortedVars() as $name => $var) {
            $out['vars'][$name] = self::var($var);
        }
        if ($out['vars'] === []) {
            $out['vars'] = new \stdClass();
        }
        if ($contract->files !== []) {
            $out['files'] = [];
            foreach ($contract->sortedFiles() as $name => $file) {
                $out['files'][$name] = self::file($file);
            }
        }
        return $out;
    }

    /** @return array<string, mixed> */
    private static function var(VarSpec $v): array
    {
        $o = ['type' => $v->type, 'description' => $v->description];
        self::common($o, $v->required, $v->secret, $v->group, $v->deprecated);
        if ($v->examples !== null) {
            $o['examples'] = $v->examples;
        }
        if ($v->configKey !== null) {
            $o['configKey'] = $v->configKey;
        }
        switch ($v->type) {
            case 'string':
                self::put($o, 'minLength', $v->minLength);
                self::put($o, 'maxLength', $v->maxLength);
                self::put($o, 'pattern', $v->pattern);
                break;
            case 'int':
            case 'float':
            case 'duration':
                if ($v->type === 'duration') {
                    $o['encoding'] = $v->encoding();
                }
                self::put($o, 'min', self::plain($v->min));
                self::put($o, 'max', self::plain($v->max));
                break;
            case 'url':
                self::put($o, 'schemes', $v->schemes);
                self::put($o, 'maxLength', $v->maxLength);
                break;
            case 'enum':
                $o['values'] = $v->values ?? [];
                break;
            case 'list':
                $o['items'] = $v->items;
                $o['encoding'] = $v->encoding();
                if ($v->encoding() === 'csv') {
                    $o['separator'] = $v->separator;
                }
                self::put($o, 'minItems', $v->minItems);
                self::put($o, 'maxItems', $v->maxItems);
                self::put($o, 'itemMin', $v->itemMin);
                self::put($o, 'itemMax', $v->itemMax);
                self::put($o, 'itemMinLength', $v->itemMinLength);
                self::put($o, 'itemMaxLength', $v->itemMaxLength);
                break;
            case 'json':
                self::put($o, 'maxLength', $v->maxLength);
                self::put($o, 'schema', $v->schema);
                break;
        }
        if ($v->hasDefault) {
            $o['default'] = self::plain($v->default);
        }
        return $o;
    }

    /** @return array<string, mixed> */
    private static function file(FileSpec $f): array
    {
        $o = ['type' => $f->type];
        if ($f->format !== null) {
            $o['format'] = $f->format;
        }
        $o['description'] = $f->description;
        self::common($o, $f->required, $f->secret, $f->group, $f->deprecated);
        $o['path'] = $f->path;
        self::put($o, 'pathEnv', $f->pathEnv);
        if ($f->reload !== 'restart') {
            $o['reload'] = $f->reload;
        }
        self::put($o, 'maxSize', $f->maxSize);
        switch ($f->type) {
            case 'config':
                self::put($o, 'schema', $f->schema);
                break;
            case 'tls':
                self::put($o, 'dnsNames', $f->dnsNames);
                self::put($o, 'keyAlgorithms', $f->keyAlgorithms);
                self::put($o, 'minRemaining', $f->minRemaining?->toString());
                if ($f->requireCA) {
                    $o['requireCA'] = true;
                }
                break;
            case 'caBundle':
                if ($f->minCertificates !== 1) {
                    $o['minCertificates'] = $f->minCertificates;
                }
                break;
            case 'keystore':
                self::put($o, 'passwordVar', $f->passwordVar);
                break;
            case 'text':
                self::put($o, 'pattern', $f->pattern);
                self::put($o, 'minLength', $f->minLength);
                self::put($o, 'maxLength', $f->maxLength);
                break;
        }
        return $o;
    }

    /**
     * @param array<string, mixed> $o
     * @param array{message: string, replacedBy?: string}|null $deprecated
     */
    private static function common(array &$o, bool $required, bool $secret, ?string $group, ?array $deprecated): void
    {
        if ($required) {
            $o['required'] = true;
        }
        if ($secret) {
            $o['secret'] = true;
        }
        self::put($o, 'group', $group);
        self::put($o, 'deprecated', $deprecated);
    }

    /** @param array<string, mixed> $o */
    private static function put(array &$o, string $key, mixed $value): void
    {
        if ($value !== null) {
            $o[$key] = $value;
        }
    }

    /** Typed values (Durations, enums, objects) as plain contract data. */
    public static function plain(mixed $value): mixed
    {
        if ($value instanceof Duration) {
            return $value->toString();
        }
        if ($value instanceof \BackedEnum) {
            return $value->value;
        }
        if (is_array($value)) {
            return array_map(self::plain(...), $value);
        }
        if ($value instanceof \stdClass) {
            return $value;
        }
        if (is_object($value)) {
            return \Docuconf\Schema\Json::normalize(json_decode(\Docuconf\Schema\Json::encode($value)));
        }
        return $value;
    }

    /** A CUE package name from a service name: "orders-api" becomes "orders_api". */
    public static function packageName(string $name): string
    {
        $pkg = preg_replace('/[^a-z0-9_]/', '_', strtolower($name)) ?? 'contract';
        return preg_match('/^[a-z]/', $pkg) ? $pkg : 'c_' . $pkg;
    }
}
