<?php

declare(strict_types=1);

namespace Docuconf\Tests;

use Docuconf\Contract;
use Docuconf\Declaration;
use Docuconf\Env;
use Docuconf\Export\Exporter;
use Docuconf\Tests\Support\CueVet;
use PHPUnit\Framework\TestCase;

final class ExportTest extends TestCase
{
    private static function fixture(): Declaration
    {
        return require __DIR__ . '/Fixtures/sample_gateway.php';
    }

    public function testMatchesTheGoldenFile(): void
    {
        $golden = __DIR__ . '/golden/sample_gateway.cue';
        if (getenv('DOCUCONF_UPDATE_GOLDEN') === '1') {
            file_put_contents($golden, self::fixture()->export());
        }
        self::assertSame(file_get_contents($golden), self::fixture()->export());
    }

    public function testGoldenFilePassesTheMetaSchema(): void
    {
        CueVet::vet((string) file_get_contents(__DIR__ . '/golden/sample_gateway.cue'));
    }

    public function testExportIsDeterministicAndSorted(): void
    {
        $a = Env::declare('svc');
        $a->ifPresent('ZED')->describe('Last variable');
        $a->ifPresent('ALPHA')->describe('First variable');
        $b = Env::declare('svc');
        $b->ifPresent('ALPHA')->describe('First variable');
        $b->ifPresent('ZED')->describe('Last variable');
        self::assertSame($a->export(), $b->export());
        self::assertLessThan(strpos($a->export(), 'ZED'), strpos($a->export(), 'ALPHA'));
    }

    public function testHeaderPackageAndImport(): void
    {
        $cue = self::fixture()->export();
        self::assertStringStartsWith("// Code generated by docuconf. DO NOT EDIT.\npackage sample_gateway\n\nimport \"docuconf.dev/contract\"\n\ncontract.#Contract & {", $cue);
        self::assertStringContainsString('language: "php"', $cue);
    }

    public function testDurationsAreCanonical(): void
    {
        $env = Env::declare('svc');
        $env->ifPresent('TIMEOUT')->isDuration('iso8601')->between('90s', '1.5h')->default('5400s')->describe('A long timeout');
        $cue = $env->export();
        self::assertStringContainsString('min: "1m30s"', $cue);
        self::assertStringContainsString('max: "1h30m"', $cue);
        self::assertStringContainsString('default: "1h30m"', $cue);
        self::assertStringContainsString('encoding: "iso8601"', $cue);
        CueVet::vet($cue);
    }

    public function testStringsAreEscaped(): void
    {
        $env = Env::declare('svc');
        $env->ifPresent('NOTE')->default("cost \$5, \"quoted\" \\(x) é\n")->describe('A tricky default');
        $cue = $env->export();
        self::assertStringContainsString('default: "cost $5, \"quoted\" \\\\(x) é\n"', $cue);
        CueVet::vet($cue);
    }

    public function testContractFirstRoundTrip(): void
    {
        // The exported contract, as JSON, loads in contract-first mode.
        $json = json_encode(Exporter::toArray(self::fixture()->spec()), JSON_THROW_ON_ERROR);
        $contract = Contract::fromJson($json);
        self::assertSame(self::fixture()->export(), $contract->toCue());
    }

    public function testCliExport(): void
    {
        $out = sys_get_temp_dir() . '/docuconf-cli-' . bin2hex(random_bytes(4)) . '.cue';
        $bin = dirname(__DIR__) . '/bin/docuconf';
        $fixture = __DIR__ . '/Fixtures/sample_gateway.php';
        exec(PHP_BINARY . ' ' . escapeshellarg($bin) . ' export ' . escapeshellarg($fixture) . ' -o ' . escapeshellarg($out) . ' 2>&1', $o, $code);
        self::assertSame(0, $code, implode("\n", $o));
        self::assertSame(file_get_contents(__DIR__ . '/golden/sample_gateway.cue'), file_get_contents($out));
        exec(PHP_BINARY . ' ' . escapeshellarg($bin) . ' export ' . escapeshellarg($fixture) . ' -o ' . escapeshellarg($out) . ' --check 2>&1', $o, $code);
        self::assertSame(0, $code);
        file_put_contents($out, 'stale');
        exec(PHP_BINARY . ' ' . escapeshellarg($bin) . ' export ' . escapeshellarg($fixture) . ' -o ' . escapeshellarg($out) . ' --check 2>&1', $o, $code);
        self::assertSame(1, $code);
        unlink($out);
    }
}
