// Code generated by docuconf. DO NOT EDIT.
package sample_gateway

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name: "sample-gateway"
		generator: {
			language: "php"
			sdk:      "docuconf/docuconf"
			version:  "0.1.0"
		}
	}
	vars: {
		ALLOWED_ORIGINS: {
			type:        "list"
			description: "CORS origins allowed to call the API"
			required:    true
			items:       "string"
			encoding:    "csv"
			separator:   ","
			minItems:    1
			maxItems:    10
		}
		DATABASE_URL: {
			type:        "url"
			description: "Primary Postgres connection string"
			required:    true
			secret:      true
			schemes: ["postgres", "postgresql"]
		}
		DEBUG: {
			type:        "bool"
			description: "Verbose request logging"
			default:     false
		}
		GOMEMLIMIT: {
			type:        "int"
			description: "Soft memory limit, in bytes"
			min:         1
		}
		KEYSTORE_PASSWORD: {
			type:        "string"
			description: "Password for the partner keystore"
			required:    true
			secret:      true
			minLength:   1
		}
		LOG_LEVEL: {
			type:        "enum"
			description: "Minimum log level emitted"
			group:       "logging"
			values: ["debug", "info", "warn", "error"]
			default: "info"
		}
		PORT: {
			type:        "int"
			description: "HTTP listen port"
			min:         1
			max:         65535
			default:     8080
		}
		PUBLIC_URL: {
			type:        "url"
			description: "Externally visible base URL"
			required:    true
			schemes: ["https"]
		}
		RATE_LIMITS: {
			type:        "json"
			description: "Default per-client rate limits"
			schema: {
				type:  "object"
				title: "RateLimits"
				properties: {
					perMinute: {
						type:    "integer"
						minimum: 1
					}
					burst: {
						type:    "integer"
						minimum: 0
						default: 0
					}
				}
				required: ["perMinute"]
				additionalProperties: false
			}
		}
		REGION: {
			type:        "string"
			description: "Cloud region the service runs in"
			required:    true
			examples: ["eu-west-1"]
			minLength: 4
			maxLength: 32
			pattern:   "^[a-z]{2}-[a-z]+-[0-9]$"
		}
		REQUEST_TIMEOUT: {
			type:        "duration"
			description: "Upstream request timeout"
			encoding:    "go"
			min:         "1s"
			max:         "5m"
			default:     "30s"
		}
		SAMPLE_RATE: {
			type:        "float"
			description: "Fraction of requests traced"
			min:         0.0
			max:         1.0
			default:     0.25
		}
		WORKER_PORTS: {
			type:        "list"
			description: "Ports the workers bind"
			items:       "int"
			encoding:    "json"
			itemMin:     1
			itemMax:     65535
			default: []
		}
	}
	files: {
		geoip: {
			type:        "binary"
			description: "GeoIP database for country-based routing"
			path:        "/data/geoip/GeoLite2-City.mmdb"
			maxSize:     134217728
		}
		license: {
			type:        "text"
			description: "Gateway licence key"
			required:    true
			path:        "/etc/gateway/license/license.key"
			pattern:     "^[A-Z0-9]{5}(-[A-Z0-9]{5}){3}\\n?$"
		}
		"partner-keystore": {
			type:        "keystore"
			format:      "pkcs12"
			description: "Client certificate for mTLS to the partner API"
			secret:      true
			path:        "/etc/gateway/partner/keystore.p12"
			passwordVar: "KEYSTORE_PASSWORD"
		}
		routes: {
			type:        "config"
			format:      "yaml"
			description: "Routing table: path prefixes and their upstreams"
			required:    true
			path:        "/etc/gateway/routes/routes.yaml"
			pathEnv:     "ROUTES_FILE"
			maxSize:     65536
			schema: {
				"$defs": {
					Route: {
						type:  "object"
						title: "Route"
						properties: {
							match: {
								type:    "string"
								pattern: "^/"
							}
							upstream: {
								type:    "string"
								pattern: "^https?://"
							}
							timeout: {
								anyOf: [
									{
										type:    "string"
										pattern: "^([0-9]+(\\.[0-9]*)?(ns|us|ms|s|m|h))+$"
									},
									{
										type: "null"
									},
								]
								default: null
							}
						}
						required: ["match", "upstream"]
						additionalProperties: false
					}
				}
				type:  "object"
				title: "Routes"
				properties: {
					routes: {
						type: "array"
						items: {
							"$ref": "#/$defs/Route"
						}
						minItems: 1
					}
				}
				required: ["routes"]
				additionalProperties: false
			}
		}
		"serving-tls": {
			type:        "tls"
			description: "Certificate the gateway serves HTTPS with"
			required:    true
			secret:      true
			path:        "/etc/gateway/tls"
			dnsNames: ["gateway.internal", "api.example.com"]
			keyAlgorithms: ["ECDSA", "RSA"]
			minRemaining: "720h"
			requireCA:    true
		}
		"upstream-ca": {
			type:        "caBundle"
			description: "Private CAs the gateway trusts for upstream TLS"
			path:        "/etc/gateway/ca/bundle.pem"
			pathEnv:     "SSL_CERT_FILE"
		}
	}
}
